<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  <title>Анализатор страниц</title>
</head>

<body class="d-flex flex-column min-vh-100">
  <header>
    <nav class="navbar navbar-expand-sm bg-dark" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand mb-1" href="/">Анализатор страниц</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active" aria-current="page" href="/">Главная</a>
            <a class="nav-link" href="/urls">Сайты</a>
          </div>
        </div>
      </div>
    </nav>
  </header>

  <main class="wrapper flex-grow-1">
    <div class="container-lg mt-3">
      <h1>Сайты</h1>
      <div class="table-responsive">
        <table class="table table-bordered table-hover text-nowrap" data-test="urls">
          <tbody>
            <tr>
              <th>ID</th>
              <th>Имя</th>
              <th>Последняя проверка</th>
              <th>Код ответа</th>
            </tr>
              <?php foreach ($urls as $urlId => $url) : ?>
                <tr>
                  <td><?= $urlId ?></td>
                  <td><a href="/urls/<?= $urlId ?>"><?= $url['name'] ?></a></td>
                  <td><?= $url['created_at'] ?? '' ?></td>
                  <td><?= $url['status_code']  ?? '' ?></td>
                </tr>
              <?php endforeach ?>
          </tbody>
        </table>
      </div>
    </div>
  </main>

  <footer class="border-top py-3 mt-3 flex-shrink-0">
    <div class="container-lg">
      <div class="text-center">
        <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
      </div>
    </div>
  </footer>
</body>

</html>