<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="bootstrap.min.css" rel="stylesheet" />
    <script src="bootstrap.bundle.min.js"></script>
    <title>Анализатор страниц</title>
</head>
<body>
<div class="container">
  <header>
    <div class="row bg-dark">
      <div class="col">
        <nav>
          <ul class="list-inline">
            <li class="list-inline-item"><a class="text-decoration-none" href="#">Анализатор страниц</a></li>
            <li class="list-inline-item"><a class="text-decoration-none" href="#">Главная</a></li>
            <li class="list-inline-item"><a class="text-decoration-none" href="#">Сайты</a></li>
          </ul>
        </nav>
      </div>
    </div>
  </header>
</div>
  <main></main>
  <footer></footer>  
</body>
</html>