<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  <title>Анализатор страниц</title>
</head>

<body class="d-flex flex-column min-vh-100">
  <header>
    <nav class="navbar navbar-expand-sm bg-dark" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand mb-1" href="/">Анализатор страниц</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active" aria-current="page" href="/">Главная</a>
            <a class="nav-link" href="/urls">Сайты</a>
          </div>
        </div>
      </div>
    </nav>
  </header>

  <?php if (count($flash) > 0) : ?>
      <?php foreach ($flash as $messages) : ?>
          <?php foreach ($messages as $message) : ?>
            <div class="alert alert-<?= $alert ?>" role="alert"><?= $message ?></div>
          <?php endforeach ?>
      <?php endforeach ?>
  <?php endif ?>

  <main class="wrapper flex-grow-1">
  <div class="container-lg mt-3">
    <h1>Сайт: <?= $page['name'] ?></h1>
    <div class="table-responsive">
      <table class="table table-bordered table-hover text-nowrap" data-test="url">
        <tbody>
          <tr>
            <td>ID</td>
            <td><?= $page['id'] ?></td>
          </tr>
          <tr>
            <td>Имя</td>
            <td><?= $page['name'] ?></td>
          </tr>
          <tr>
            <td>Дата создания</td>
            <td><?= $page['created_at'] ?></td>
          </tr>
        </tbody>
      </table>
    </div>
    <h2 class="mt-5 mb-3">Проверки</h2>
    <form method="post" action="/urls/<?= $page['id'] ?>/checks">
      <input type="submit" class="btn btn-primary" value="Запустить проверку">
    </form>
    <table class="table table-bordered table-hover" data-test="checks">
      <tbody>
        <tr>
          <th>ID</th>
          <th>Код ответа</th>
          <th>h1</th>
          <th>title</th>
          <th>description</th>
          <th>Дата создания</th>
        </tr>
        <?php foreach ($checks as $check) : ?>
          <tr>
            <td><?= $check['id'] ?? '' ?></td>
            <td><?= $check['status_code'] ?? '' ?></td>
            <td><?= $check['h1'] ?? '' ?></td>
            <td><?= $check['title'] ?? '' ?></td>
            <td><?= $check['description'] ?? '' ?></td>
            <td><?= $check['created_at'] ?? '' ?></td>
          </tr>
        <?php endforeach ?>
      </tbody>
    </table>
  </div>
  </main>

  <footer class="border-top py-3 mt-3 flex-shrink-0">
    <div class="container-lg">
      <div class="text-center">
        <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
      </div>
    </div>
  </footer>
</body>

</html>